### ISSUE TITLE
still not working

### ISSUE THREAD

**Issue by xMOD3** [onemanbuilds/TikTokUsernameChecker#4]
![Screenshot_1](https://user-images.githubusercontent.com/51008831/98275376-9da78b00-1fa5-11eb-8c6b-ac52d886c6bb.png)

**Comment by onemanbuilds** [comment]
1. Download the zip with the exe. 2. If you want to use proxies put them in the proxies.txt 3.Unzip the .zip file then run the exe. 4. Don't use more then 300 threads.

**Comment by xMOD3** [comment]
do you have discord?

**Comment by onemanbuilds** [comment]
onemanbuilds#2108
